<a href="https://colab.research.google.com/github/RaphaelBau/Simulaci-n-/blob/main/SerpientesyEscaleras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Serpientes y Escaleras


Las instrucciones son las tradicionales, se juega con un dado justo de 6 caras.

Sea N el número de lanzamientos requerido para alcanzar el final del juego (llegar a la casilla final).

# Determinar el valor esperado de N
![image.png](attachment:fd2079ae-18ef-449a-9972-c8e8adc4e080.png)

## Analíticamente

Consideremos la cadena de Markov con espacio de estados $S = \{0,1,2,3,...,20\}$, en donde cada estado representa la posición en el tablero, siendo el estado **0** en donde no hemos empezado a jugar.  

Consideremos que si me encuentro en la posición **i**, a lo maximo puedo avanzar a **i+6** porque el dado tiene 6 caras, cada una con probabilidad de $\frac{1}{6}$, considerando que el dado es justo y no esta cargado. Además consideremos que no requerimos que la cantidad de pasos exacta para llegar a la meta, es decir, si se pasa de la casilla **FINAL**, se considerara como **GANADOR**.

Es así como la matriz de transición de esta cadena de Markov (sin considerar aun las escaleras y las serpientes) nos quedaria como:

\begin{equation*}
P =
\begin{bmatrix}
0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & \frac{1}{6}  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6}  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 &\frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}& 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}& 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0  & 0 & 0  & 0 & 0  & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0 & 0 & 0 & 0 & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0 & 0 & 0 & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0 & 0 & 0\\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0 & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{2}{6} \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{3}{6} \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{4}{6} \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{5}{6} \\
0 & 0  & 0 & 0  & 0 & 0 & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 1 \\
0 & 0  & 0 & 0  & 0 & 0 & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 1 \\
\end{bmatrix}
\end{equation*}


### A continuacion agregamos las Serpientes y Escaleras
Pensemos que estamos en el estado **0**, es decir, apenas comenzara el juego, la probabilidad de que caigamos en el estado **3** viniendo del estado **0** es **$P_{0,3}=\frac{1}{6}$**, sin embargo, es facil ver que el estado 3 nos conecta directamente al estado **11**, se cambiaria a **$P_{0,3}=0$** y **$P_{0,11}=\frac{1}{6}$**. Lo mismo ocurriria con las serpientes.

Entonces la matriz de transición P considerando las **Serpientes y Escaleras** quedaria de la forma siguiente:
\begin{equation*}
P =
\begin{bmatrix}
0 & \frac{1}{6} & \frac{1}{6} & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0  & 0 & 0  & 0 & \frac{1}{6}  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & \frac{1}{6} & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & 0 & 0  & 0 & \frac{1}{6}  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & 0  & 0 & \frac{1}{6}  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & \frac{1}{6}  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6} & \frac{1}{6}  & \frac{1}{6}  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 &\frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6}& 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0  & 0 & 0  & \frac{1}{6} & 0  & 0 & 0  & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0 & 0 & 0  & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0  & \frac{1}{6} & 0  & 0 & 0  & 0 & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0 & \frac{1}{6} & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0  & 0 & 0  & \frac{1}{6} & 0  & 0 & 0  & 0 & 0  & \frac{1}{6} & \frac{1}{6} & \frac{1}{6} & 0 & \frac{1}{6} & 0 & 0 & 0 & 0 & \frac{1}{6} & 0 \\
0 & 0  & 0 & 0  & \frac{1}{6} & 0  & 0 & 0  & 0 & 0  & 0 & \frac{1}{6} & \frac{1}{6} & 0 & \frac{1}{6} & 0 & \frac{1}{6} & 0 & 0 & \frac{1}{6} & 0 \\
0 & 0  & 0 & 0  & \frac{1}{6} & 0  & 0 & 0  & 0 & 0  & \frac{1}{6} & 0 & \frac{1}{6} & 0 & \frac{1}{6} & 0 & \frac{1}{6} & 0 & 0 & \frac{1}{6} & 0\\
0 & 0  & 0 & 0  & \frac{1}{6} & 0  & 0 & 0  & 0 & 0  & \frac{1}{6} & 0 & 0 & 0 & \frac{1}{6} & 0 & \frac{1}{6} & 0 & \frac{1}{6} & \frac{1}{6} & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & \frac{1}{6} & 0 & 0 & 0 & \frac{1}{6} & 0 & \frac{1}{6} & 0 & \frac{1}{6} & \frac{2}{6} & 0 \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & \frac{1}{6} & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & 0 & \frac{1}{6} & \frac{2}{6} & \frac{1}{6} \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & \frac{1}{6} & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & 0 & \frac{1}{6} & \frac{1}{6} & \frac{2}{6} \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & \frac{1}{6} & 0 & 0 & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{3}{6} \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{1}{6} & \frac{4}{6} \\
0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & \frac{1}{6} & \frac{5}{6} \\
0 & 0  & 0 & 0  & 0 & 0 & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 1 \\
0 & 0  & 0 & 0  & 0 & 0 & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0  & 0 & 0 & 0 & 0 & 1 \\
\end{bmatrix}
\end{equation*}



Consideremos que una cadena de Markov se llama **absorbente** si tiene al menos un estado absorbente.

Es fácil ver que la cadena de Markov asociada al juego mencionado tiene un estado absorbente. Si estoy en el estado **20**, la probabilidad es \(P_{20,20}=1\), ya que si llego a la última casilla, no importa si vuelvo a tirar el dado, ya he ganado y seguiré en ese estado.

Dado lo anterior, podemos ver la matriz **P** de la siguiente manera:
\begin{equation*}
P =
\begin{bmatrix}
\textbf{Q} & \textbf{R} \\
\textbf{0} & \textbf{I} \\
\end{bmatrix}
\end{equation*}

Sea
\begin{equation*}
S = (\textbf{I}-\textbf{Q})^{-1}
\end{equation*}
en donde $S_{i,j}$ denota el númerom esperado de visitas al estado j dado que la cadena de Markov inicia en el estado i. Considerando que la matriz **Q** es una matriz $txt$ en donde **t := la cantidad de estados transitorios**.


Para determinar la cantidad de lanzamientos requeridos para ganar el juego basta con sumar la primer fila de **S**, ya que cada entrada **$S_{0,j}$**   nos daria la cantidad de lanzamientos totales que estariamos en el estado **j** (transitorios) viniendo del estado **0**, es decir, al sumar todas las entradas obtendriamos la cantidad de lanzmaientos antes de llegar al estado **absorbente**, o sea, **GANAR**.



Por practicidad, obtendremos la matriz **S** con ayuda de la herramienta de programación que se muestra a continuación.

In [ ]:
import numpy as np
import pandas as pd

# Definimos la matriz de transición
P = np.zeros((21, 21))

esca = [3, 15]  # Caemos en esta casilla
sube = [11, 19]  # Nos manda a la casilla correspondiente

serp = [13, 17]  # Caemos en la cola de la serpiente
baja = [4, 10]  # Nos manda a la cabeza correspondiente

# Llenamos la matriz de valores
for i in range(21):
    for j in range(21):
        if j > i and j <= i + 6:
            P[i, j] = 1/6
        else:
            P[i, j] = 0


for i in range(21):
    for j in range(21):
        if P[i, j] != 0:
            for k in range(2):
                if j == esca[k] :
                    P[i, j] = 0
                    P[i, sube[k]] = 1/6
                elif j == serp[k] :
                    P[i, j] = 0
                    P[i, baja[k]] = 1/6
P[13,19]=2/6
P[14,19]=2/6
P[15,20]=2/6
P[16,20]=3/6
P[17,20]=4/6
P[18,20]=5/6
P[19,20]=1
P[20, 20] = 1
#print(P)



# Obtenemos Q excluyendo la ultima fila y columna de P
Q = P[0:20, 0:20]
I = np.identity(Q.shape[0])  # Matriz identidad del mismo tamaño que Q
# Calculamos I - Q
A = I - Q
S = np.linalg.inv(A)
print("Matriz S:")
print(S)

N_esperado = np.sum(S[0, :])
print("La cantidad de juegos (N) esperado para ganar el juego es: ", N_esperado)

Matriz S:
[[1.         0.16666667 0.19444444 0.         0.6817699  0.34048017
  0.39722686 0.29676467 0.31844767 0.33911488 0.7025546  0.62594999
  0.44667645 0.         0.40545726 0.         0.36343972 0.
  0.20259557 0.58187429]
 [0.         1.         0.16666667 0.         0.66897572 0.3059404
  0.35693046 0.41641888 0.31915535 0.34457014 0.70659871 0.60271343
  0.45773116 0.         0.40512813 0.         0.36202857 0.
  0.20414798 0.58134104]
 [0.         0.         1.         0.         0.64747173 0.27457862
  0.32034173 0.37373201 0.43602068 0.34202413 0.70061912 0.57455272
  0.45788173 0.         0.4185164  0.         0.358595   0.
  0.20583219 0.57942295]
 [0.         0.         0.         1.         0.65650392 0.27608399
  0.32209799 0.37578098 0.43841115 0.51147967 0.70871567 0.43876157
  0.4658745  0.         0.42720709 0.         0.34009314 0.
  0.20552912 0.58747798]
 [0.         0.         0.         0.         1.47560203 0.24593367
  0.28692262 0.33474305 0.39053356 0.45

## Simulación de Serpientes y escaleras

In [3]:
import random

N = 50000
victoria = 20
N_esperado = []

for j in range(21):
    tiros = []
    for i in range(1, N + 1):
        posicion = j
        contador = 0
        while posicion < victoria:
            dado = random.randint(1, 6)
            posicion += dado
            if posicion == 3:
                posicion = 11
            if posicion == 15:
                posicion = 19
            if posicion == 17:
                posicion = 10
            if posicion == 13:
                posicion = 4
            contador += 1
        tiros.append(contador)

    N_esperado.append(sum(tiros) / N)

print("La cantidad de lanzamientos esperados (N) para ganar el juego es: ", round(N_esperado[0],2))

La cantidad de lanzamientos esperados (N) para ganar el juego es:  7.05


In [4]:
import random

N = 50000
victoria = 20
N_esperado = []
esca = [3, 15]  # Caemos en esta casilla
sube = [11, 19]  # Nos manda a la casilla correspondiente

serp = [13, 17]  # Caemos en la cola de la serpiente
baja = [4, 10]  # Nos manda a la cabeza correspondiente

for j in range(21):
    tiros = []
    for i in range(1, N + 1):
        posicion = j
        contador = 0
        while posicion < victoria:
            dado = random.randint(1, 6)
            posicion += dado
            for k in range(2):
                if posicion == esca[k] :
                    posicion = sube[k]
                elif posicion == serp[k] :
                    posicion = baja[k]
            contador += 1
        tiros.append(contador)

    N_esperado.append(sum(tiros) / N)

print("La cantidad de lanzamientos esperados (N) para ganar el juego es: ", round(N_esperado[0],2))

La cantidad de lanzamientos esperados (N) para ganar el juego es:  7.08


# Conclusiones
Como hemos podido observar, la solución mediante simulación resulta considerablemente más sencilla que la solución analítica. Además, la diferencia entre la solución obtenida por simulación y la solución analítica es mínima. Específicamente en este ejercicio, la simulación fue más accesible para nosotros, mientras que la solución analítica requiere un mayor dominio de procesos estocásticos, especialmente en lo que respecta a cadenas de Markov y la matriz fundamental, entre otros aspectos. Es importante destacar que la obtención de la matriz S se realizó con la ayuda de herramientas de programación, ya que calcularla manualmente habría implicado demasiado tiempo. Este hecho resalta otro punto importante a favor de la simulación: en muchas ocasiones, la teoría por sí sola no es suficiente o resulta demasiado compleja y difícil de comprender, mientras que la simulación facilita este proceso.

# Serpientes y escaleras de 100 casillas ANALÍTICA

In [8]:
import numpy as np
import pandas as pd

# Definimos la matriz de transición
P = np.zeros((101, 101))

esca = [1,3,4,9,21,28,36,51,71,80] #Caemos en esta casilla
sube = [38,3,14,31,42,84,44,67,91,100] #Nos manda a la casilla correspondiente

serp = [16, 49, 62, 87, 48, 56, 64, 93, 95, 98] #Caemos en la cola de la serpiente
baja = [6, 11, 19, 24, 26, 53, 60, 73, 75, 78] #Nos manda a la cabeza correspindiente
#Ejemplo, si caigo en la 96, me manda a la 69. Si caigo en la 18, me manda a su
#correspondiente que es 6.

# Llenamos la matriz de valores
for i in range(101):
    for j in range(101):
        if j > i and j <= i + 6:
            P[i, j] = 1/6
        else:
            P[i, j] = 0


for i in range(101):
    for j in range(101):
        if P[i, j] != 0:
            for k in range(10):
                if j == esca[k] :
                    P[i, j] = 0
                    P[i, sube[k]] = 1/6
                elif j == serp[k] :
                    P[i, j] = 0
                    P[i, baja[k]] = 1/6
P[50,53]=2/6
P[51,53]=2/6
P[52,53]=2/6
P[58,60]=2/6
P[59,60]=2/6

#P[14,19]=2/6


P[95,100]=2/6
P[96,100]=3/6
P[97,100]=4/6
P[98,100]=5/6
P[99,100]=1
P[100, 100] = 1



# Obtenemos Q excluyendo la ultima fila y columna de P
Q = P[0:100, 0:100]
I = np.identity(Q.shape[0])  # Matriz identidad del mismo tamaño que Q
# Calculamos I - Q
A = I - Q
S = np.linalg.inv(A)
print("Matriz S:")
print(S)

N_esperado = np.sum(S[0, :])
print("La cantidad de juegos (N) esperado para ganar el juego es: ", round(N_esperado, 2))

Matriz S:
[[1.         0.         0.16666667 ... 0.27987985 0.         0.16015443]
 [0.         1.         0.16666667 ... 0.28052781 0.         0.16086565]
 [0.         0.         1.         ... 0.28054875 0.         0.16088874]
 ...
 [0.         0.         0.         ... 1.04084309 0.         0.19110876]
 [0.         0.         0.         ... 0.         1.         0.16666667]
 [0.         0.         0.         ... 0.         0.         1.        ]]
La cantidad de juegos (N) esperado para ganar el juego es:  36.19


In [9]:
def suma_filas(matriz):
    sumas = []
    for fila in matriz:
        suma_fila = sum(fila)
        sumas.append(suma_fila)
    return sumas

# Ejemplo de una matriz de entradas

# Calcular la suma de cada fila
sumas_filas = suma_filas(P)

# Imprimir los resultados
#for i, suma in enumerate(sumas_filas):
    #print("La suma de la fila", i, "es:", suma)

# Serpientes y escaleras de 100 casillas SIMULACIÓN

In [10]:
import random

N = 50000
victoria = 100
N_esperado = []
esca = [1,3,4,9,21,28,36,51,71,80] #Caemos en esta casilla
sube = [38,3,14,31,42,84,44,67,91,100] #Nos manda a la casilla correspondiente

serp = [16, 49, 62, 87, 48, 56, 64, 93, 95, 98] #Caemos en la cola de la serpiente
baja = [6, 11, 19, 24, 26, 53, 60, 73, 75, 78] #Nos manda a la cabeza correspindiente
#Ejemplo, si caigo en la 96, me manda a la 69. Si caigo en la 18, me manda a su
#correspondiente que es 6.

for j in range(100):
    tiros = []
    for i in range(1, N + 1):
        posicion = j
        contador = 0
        while posicion < victoria:
            dado = random.randint(1, 6)
            posicion += dado
            for k in range(10):
                if posicion == esca[k] :
                    posicion = sube[k]
                elif posicion == serp[k] :
                    posicion = baja[k]
            contador += 1
        tiros.append(contador)

    N_esperado.append(sum(tiros) / N)

print("La cantidad de lanzamientos esperados (N) para ganar el juego es: ", round(N_esperado[0], 2))

La cantidad de lanzamientos esperados (N) para ganar el juego es:  36.02
